name: browser-store-test-data build and deploy

on:
  push:
    branches: [ main ]

jobs:
  transpile:
    name: Transpile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Transpile Code
        run: npm run compile

  deploy:
    name: Deploy
    needs: transpile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Prepare release
        run: npm run prepare
      - name: Release
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm run release
        with:
          token: ${{ secrets.NPM_TOKEN }}
